import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

function productSidebar(dirName: string, title: string) {
  return [
    {type: 'link' as const, label: '← Home', href: '/'},
    {type: 'html' as const, value: `<div class="sidebar-product-title">${title}</div>`},
    {type: 'autogenerated' as const, dirName},
  ];
}

const sidebars: SidebarsConfig = {
  platformSidebar: productSidebar('bitrise-platform', 'Bitrise as a Platform'),
  ciSidebar: productSidebar('bitrise-ci', 'Bitrise CI'),
  buildCacheSidebar: productSidebar('bitrise-build-cache', 'Build Cache'),
  releaseManagementSidebar: productSidebar('release-management', 'Release Management'),
  insightsSidebar: productSidebar('insights', 'Insights'),
  buildHubSidebar: productSidebar('bitrise-build-hub', 'Build Hub'),
};

export default sidebars;
