import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import bitriseAPIApiSidebar from './docs/bitrise-api/api-reference/sidebar';
import rdeAPIApiSidebar from './docs/bitrise-rde-api/api-reference/sidebar';
import rmAppsApiSidebar from './docs/release-management-api/apps/api-reference/sidebar';
import rmStoreReleasesApiSidebar from './docs/release-management-api/store-releases/api-reference/sidebar';
import rmCodePushApiSidebar from './docs/release-management-api/code-push/api-reference/sidebar';
import rmBuildDistributionsApiSidebar from './docs/release-management-api/build-distributions/api-reference/sidebar';

function productSidebar(dirName: string, title: string) {
  return [
    {type: 'link' as const, label: '← Home', href: '/'},
    {type: 'html' as const, value: `<div class="sidebar-product-title">${title}</div>`},
    {type: 'autogenerated' as const, dirName},
  ];
}

// Convert kebab-case tag labels to sentence case and fix known quirks.
function normalizeLabel(label: string): string {
  // kebab-case → sentence case
  const spaced = label.replace(/-/g, ' ');
  const capitalized = spaced.charAt(0).toUpperCase() + spaced.slice(1);
  // Capitalize standalone "api" → "API"
  return capitalized.replace(/\bapi\b/gi, 'API');
}

// Corrections applied after normalization for compound words that need a hyphen.
const TAG_LABEL_OVERRIDES: Record<string, string> = {
  'Key value cache': 'Key-value cache',
};

// Normalize a generated openapi sidebar (tag categories) into hub items:
// sentence-case the tag labels and tag every entry with the "Code" icon. The
// generated info doc has no label and is filtered out (added explicitly below).
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function toHubItems(generated: any, addIcon = true) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return (generated as any[]).filter((item: any) => item.label).map(item => {
    const originalLabel = item.label as string | undefined;
    const correctedLabel = originalLabel
      ? (() => { const n = normalizeLabel(originalLabel); return TAG_LABEL_OVERRIDES[n] ?? n; })()
      : originalLabel;
    return {
      ...item,
      ...(correctedLabel !== undefined ? {label: correctedLabel} : {}),
      ...(addIcon ? {customProps: {...(item.customProps ?? {}), icon: 'Code'}} : {}),
    };
  });
}

const hubItems = toHubItems(bitriseAPIApiSidebar);
const rdeHubItems = toHubItems(rdeAPIApiSidebar, false);
const rmAppsHubItems = toHubItems(rmAppsApiSidebar, false);
const rmStoreReleasesHubItems = toHubItems(rmStoreReleasesApiSidebar, false);
const rmCodePushHubItems = toHubItems(rmCodePushApiSidebar, false);
const rmBuildDistributionsHubItems = toHubItems(rmBuildDistributionsApiSidebar, false);

const sidebars: SidebarsConfig = {
  platformSidebar: productSidebar('bitrise-platform', 'Bitrise as a Platform'),
  ciSidebar: productSidebar('bitrise-ci', 'Bitrise CI'),
  buildCacheSidebar: productSidebar('bitrise-build-cache', 'Build Cache'),
  releaseManagementSidebar: [
    ...productSidebar('release-management', 'Release Management'),
    {
      type: 'category',
      label: 'API reference',
      collapsed: true,
      customProps: {icon: 'Code'},
      items: [
        {
          type: 'category',
          label: 'Apps',
          items: [
            {
              type: 'doc',
              id: 'release-management-api/apps/api-reference/release-management-api',
              label: 'Introduction',
            },
            ...rmAppsHubItems,
          ],
        },
        {
          type: 'category',
          label: 'Store releases',
          items: [
            {
              type: 'doc',
              id: 'release-management-api/store-releases/api-reference/release-management-api-app-versions',
              label: 'Introduction',
            },
            ...rmStoreReleasesHubItems,
          ],
        },
        {
          type: 'category',
          label: 'CodePush',
          items: [
            {
              type: 'doc',
              id: 'release-management-api/code-push/api-reference/release-management-api-codepush',
              label: 'Introduction',
            },
            ...rmCodePushHubItems,
          ],
        },
        {
          type: 'category',
          label: 'Build distributions',
          items: [
            {
              type: 'doc',
              id: 'release-management-api/build-distributions/api-reference/release-management-api-build-distributions',
              label: 'Introduction',
            },
            ...rmBuildDistributionsHubItems,
          ],
        },
      ],
    },
  ],
  insightsSidebar: productSidebar('insights', 'Insights'),
  buildHubSidebar: productSidebar('bitrise-build-hub', 'Build Hub'),
  rdeSidebar: [
    ...productSidebar('bitrise-rde', 'Remote Dev Environments'),
    {
      type: 'category',
      label: 'API reference',
      collapsed: true,
      customProps: {icon: 'Code'},
      items: [
        {
          type: 'doc',
          id: 'bitrise-rde-api/api-reference/bitrise-remote-dev-environments-api',
          label: 'Introduction',
        },
        ...rdeHubItems,
      ],
    },
  ],
  bitriseAPISidebar: [
    {type: 'link', label: '← Home', href: '/'},
    {type: 'html', value: '<div class="sidebar-product-title">Bitrise API</div>'},
    {type: 'doc', id: 'bitrise-api/index', label: 'Bitrise API', customProps: {icon: 'Book'}},
    {type: 'doc', id: 'bitrise-api/api-reference/bitrise-api', label: 'Introduction', customProps: {icon: 'Book'}},
    ...hubItems,
  ],
};

export default sidebars;
