import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import bitriseAPIApiSidebar from './docs/bitrise-api/api-reference/sidebar';

function productSidebar(dirName: string, title: string) {
  return [
    {type: 'link' as const, label: '← Home', href: '/'},
    {type: 'html' as const, value: `<div class="sidebar-product-title">${title}</div>`},
    {type: 'autogenerated' as const, dirName},
  ];
}

// Capitalize standalone "api" → "API" in generated tag labels.
function normalizeLabel(label: string): string {
  return label.replace(/\bapi\b/gi, 'API');
}

// Hyphens that were part of compound words get lost when the plugin converts
// kebab-case tags to space-separated labels. Declare the corrections explicitly.
const TAG_LABEL_OVERRIDES: Record<string, string> = {
  'Key value cache': 'Key-value cache',
};

const TAG_ICONS: Record<string, string> = {
  'Addons': 'Power',
  'Application': 'Dashboard',
  'App setup': 'Configure',
  'Android keystore file': 'CodeSigning',
  'Builds': 'Build',
  'Build certificate': 'SecurityShield',
  'Build request': 'ArrowsHorizontal',
  'Build artifact': 'Deployment',
  'Key value cache': 'Memory',
  'Generic project file': 'Folder',
  'Outgoing webhook': 'Cycle',
  'Webhook delivery item': 'ArrowsHorizontal',
  'Pipelines': 'WorkflowFlow',
  'Provisioning profile': 'CodeSigning',
  'Secrets': 'SecurityShield',
  'Test devices': 'Terminal',
  'Configuration': 'Configure',
  'Groups': 'Group',
  'User': 'Person',
  'Activity': 'Insights',
  'Organizations': 'Group',
  'Google service credentials': 'SecurityShield',
  'Apple api credentials': 'SecurityShield',
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const hubItems = (bitriseAPIApiSidebar as any[]).map(item => {
  const originalLabel = item.label as string;
  const correctedLabel = normalizeLabel(TAG_LABEL_OVERRIDES[originalLabel] ?? originalLabel);
  return {
    ...item,
    label: correctedLabel,
    customProps: {
      ...(item.customProps ?? {}),
      icon: 'Code',
    },
  };
});

const sidebars: SidebarsConfig = {
  platformSidebar: productSidebar('bitrise-platform', 'Bitrise as a Platform'),
  ciSidebar: productSidebar('bitrise-ci', 'Bitrise CI'),
  buildCacheSidebar: productSidebar('bitrise-build-cache', 'Build Cache'),
  releaseManagementSidebar: productSidebar('release-management', 'Release Management'),
  insightsSidebar: productSidebar('insights', 'Insights'),
  buildHubSidebar: productSidebar('bitrise-build-hub', 'Build Hub'),
  bitriseAPISidebar: [
    {type: 'link', label: '← Home', href: '/'},
    {type: 'html', value: '<div class="sidebar-product-title">Bitrise API</div>'},
    ...hubItems,
  ],
};

export default sidebars;
