import React from 'react';
import OriginalDocItem from '@theme-original/DocItem';
import ApiItem from '@theme/ApiItem';
import { HtmlClassNameProvider } from '@docusaurus/theme-common';

/**
 * Swizzled DocItem: routes pages that have `api` frontmatter (generated by
 * docusaurus-plugin-openapi-docs) to ApiItem, which sets up the Redux store
 * and Provider required by the openapi-docs theme components.
 *
 * Also adds `api-reference-page` to the <html> element so CSS can target
 * API pages specifically (e.g. to expand the content column to full width).
 *
 * (The auto-generated <SeeAlso> section lives in the DocItem/Paginator
 * swizzle, so it renders between the article content and the Previous/Next
 * buttons rather than after them.)
 */
export default function DocItem(props) {
  const { api } = props.content.frontMatter ?? {};
  if (api !== undefined) {
    return (
      <HtmlClassNameProvider className="api-reference-page">
        <ApiItem {...props} />
      </HtmlClassNameProvider>
    );
  }
  return <OriginalDocItem {...props} />;
}
