#!/usr/bin/env python3
"""
strip_en_prefix.py — remove the leading /en/ from internal doc links
=====================================================================
Historically every internal link in this repo was written as an absolute
path starting with /en/ (e.g. `[text](/en/bitrise-ci/foo)`), because the
site only ever had one locale and `/en/` was baked into every URL via
`routeBasePath: 'en'`.

Adding a second locale (ja) exposed a real problem with that convention:
`routeBasePath` is locale-independent — it applies the same static prefix
regardless of which locale is rendering, so an authored `/en/foo` link
inside a Japanese page resolves to `/ja/en/foo`, which doesn't exist.

The fix (paired with the docusaurus.config.ts change in this same PR) is to
stop hardcoding the locale in content at all: routeBasePath becomes '',
each locale gets its own baseUrl (i18n.localeConfigs[locale].baseUrl), and
internal links become locale-less bare absolute paths (`/bitrise-ci/foo`).
Docusaurus resolves a bare path against whichever locale is currently
building, correctly, for both translated and English-fallback pages —
verified directly against a real build before writing this script.

This script performs that one-time, repo-wide rewrite. It is NOT part of
the ongoing translation pipeline — once source links are prefix-free, a
translated copy inherits that for free, as long as whatever produces the
translations passes URLs through unmodified.

Scope:
  - Walks docs/, src/partials/, and i18n/*/docusaurus-plugin-content-docs/
    current/ for .md/.mdx files, plus every docs/**/_category_.json.
  - Skips any path containing /api-reference/ — those files are
    auto-generated by `npm run gen-api-docs` and overwritten on every run;
    editing them here would be silently discarded. (Verified separately:
    zero /en/ links exist in generated API-reference output anyway.)
  - Strips three link forms:
      1. Markdown links: ](/en/...  ->  ](/...
      2. JSX-prop / object-literal hrefs used by the section index pages
         (docs/*/index.mdx), e.g. overviewHref="/en/..." or href: '/en/...'
      3. Sidebar-metadata link values in _category_.json customProps
         (appendApiHubLink / isApiHubLink). These become sidebar `link`
         items, and Docusaurus's <Link> prepends the current locale's
         baseUrl to any path starting with "/" — so a leftover /en/ here
         renders as /en/en/... and breaks in *every* locale, English
         included. Only warns at build time (onBrokenLinks: 'warn'), which
         is exactly why it needs to be in this script's scope.
  - Never touches a fully-qualified URL (https://...), even one pointing at
    this same site — those are a different (and separate) content-quality
    issue, not this script's job.
  - Skips fenced code blocks and inline code, so a doc that shows /en/foo
    as example text in a code sample is left untouched.
  - Idempotent: a second run finds nothing left to strip.

Usage:
  python3 scripts/strip_en_prefix.py            # apply across docs/, src/partials/, i18n/
  python3 scripts/strip_en_prefix.py --dry-run   # report file counts, write nothing
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET_DIRS = [
    ROOT / "docs",
    ROOT / "src" / "partials",
    ROOT / "i18n",
]

# Markdown-link form ](/en/...) — anchored so it can only ever strip a link
# TARGET that starts with /en/, never a substring like /environment/ (the
# second slash right after "en" makes the segment exact).
LINK_RE = re.compile(r"\]\(/en/")

# Section index pages (docs/*/index.mdx) use JSX props / object-literal href
# values instead of markdown links, e.g. overviewHref="/en/x" or
# href: '/en/x'. Matches any ...Href="/en/ or href: '/en/ form. Deliberately
# does NOT match fully-qualified https://.../en/... links.
JSX_HREF_RE = re.compile(r"([Hh]ref[=:]\s*['\"])/en/")

# Sidebar-metadata link values in docs/**/_category_.json customProps, e.g.
# "appendApiHubLink": "/en/bitrise-api". Keyed on a trailing "Link" so it
# covers appendApiHubLink / isApiHubLink and any future sibling, without
# touching unrelated string values.
JSON_LINK_RE = re.compile(r"(\"[A-Za-z0-9_]*Link\"\s*:\s*\")/en/")

# Every pattern strips the "en/" segment and keeps the leading slash: these
# are absolute paths, and a path that loses its slash silently becomes
# relative to the current page instead (which happens to look right on a hub
# landing page and wrong everywhere else).
REPLACEMENT = {LINK_RE: "](/", JSX_HREF_RE: r"\1/", JSON_LINK_RE: r"\1/"}

CODE_FENCE_RE = re.compile(r"```.*?```|~~~.*?~~~", re.DOTALL)
INLINE_CODE_RE = re.compile(r"`[^`\n]*`")


def strip_file(path: Path, dry_run: bool) -> bool:
    if "/api-reference/" in str(path):
        return False

    # JSON carries no prose, so there is no code-fence/inline-code context to
    # protect — and no markdown or JSX link forms to look for either.
    is_json = path.suffix == ".json"
    patterns = [JSON_LINK_RE] if is_json else [LINK_RE, JSX_HREF_RE]

    text = path.read_text(encoding="utf-8")
    if not any(p.search(text) for p in patterns):
        return False

    protected = []
    if not is_json:
        for m in CODE_FENCE_RE.finditer(text):
            protected.append((m.start(), m.end()))
        for m in INLINE_CODE_RE.finditer(text):
            protected.append((m.start(), m.end()))

    def in_protected(pos):
        return any(s <= pos < e for s, e in protected)

    matches = sorted(
        [m for p in patterns for m in p.finditer(text)],
        key=lambda m: m.start(),
    )

    out = []
    last = 0
    changed = False
    for m in matches:
        if in_protected(m.start()):
            continue
        out.append(text[last:m.start()])
        out.append(m.expand(REPLACEMENT[m.re]))
        last = m.end()
        changed = True
    out.append(text[last:])

    if changed and not dry_run:
        path.write_text("".join(out), encoding="utf-8")
    return changed


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    count = 0
    for d in TARGET_DIRS:
        if not d.exists():
            continue
        for path in d.rglob("*.md*"):
            if strip_file(path, args.dry_run):
                count += 1
        for path in d.rglob("_category_.json"):
            if strip_file(path, args.dry_run):
                count += 1

    verb = "Would strip" if args.dry_run else "Stripped"
    print(f"{verb} links in {count} file(s)")


if __name__ == "__main__":
    main()
